on:
  push:
    branches:
      - actions
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
            java-version: 17
            distribution: adopt
            jdk-package: jdk
    - name: Build and package with Maven
      run: mvn package -DmainClass=pruebas.Main
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: platzi_downloader-1.0-SNAPSHOT.jar
        path: target/platzi_downloader-1.0-SNAPSHOT.jar
